// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CNCliente.Models
{
    public partial class cae
    {
        public cae()
        {
            cliente = new HashSet<cliente>();
        }

        [Key]
        public int caeId { get; set; }
        [Required]
        public string caeCodigo { get; set; }
        [Required]
        public string caeNome { get; set; }

        [InverseProperty("cae")]
        public virtual ICollection<cliente> cliente { get; set; }
    }
}