// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CNCliente.Models
{
    [Index(nameof(clienteId), Name = "IX_cliente")]
    public partial class cliente
    {
        public cliente()
        {
            projeto = new HashSet<projeto>();
        }

        [Key]
        public int clienteId { get; set; }
        public string clienteErpid { get; set; }
        public string clienteNipc { get; set; }
        [Required]
        public string clienteNome { get; set; }
        public string clienteEmail { get; set; }
        public string clienteTelefone { get; set; }
        public int? dimensao_Id { get; set; }
        public int? regiao_Id { get; set; }
        public int? setor_Id { get; set; }
        public int? cae_Id { get; set; }
        public int? codpostal_Id { get; set; }
        public int? distrito_Id { get; set; }
        public int? concelho_Id { get; set; }

        [ForeignKey(nameof(cae_Id))]
        [InverseProperty("cliente")]
        public virtual cae cae { get; set; }
        [ForeignKey(nameof(codpostal_Id))]
        [InverseProperty("cliente")]
        public virtual codpostal codpostal { get; set; }
        [ForeignKey(nameof(concelho_Id))]
        [InverseProperty("cliente")]
        public virtual concelho concelho { get; set; }
        [ForeignKey(nameof(dimensao_Id))]
        [InverseProperty("cliente")]
        public virtual dimensao dimensao { get; set; }
        [ForeignKey(nameof(distrito_Id))]
        [InverseProperty("cliente")]
        public virtual distrito distrito { get; set; }
        [ForeignKey(nameof(regiao_Id))]
        [InverseProperty("cliente")]
        public virtual regiao regiao { get; set; }
        [ForeignKey(nameof(setor_Id))]
        [InverseProperty("cliente")]
        public virtual setor setor { get; set; }
        [InverseProperty("cliente")]
        public virtual ICollection<projeto> projeto { get; set; }
    }
}