// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CNCliente.Models
{
    public partial class codpostal
    {
        public codpostal()
        {
            cliente = new HashSet<cliente>();
        }

        [Key]
        public int codpostalId { get; set; }
        public int distrito_Id { get; set; }
        public int concelho_Numero { get; set; }
        [Required]
        public string concelho_Codigo { get; set; }
        public int concelho_Id { get; set; }

        [ForeignKey(nameof(concelho_Id))]
        [InverseProperty("codpostal")]
        public virtual concelho concelho { get; set; }
        [ForeignKey(nameof(distrito_Id))]
        [InverseProperty("codpostal")]
        public virtual distrito distrito { get; set; }
        [InverseProperty("codpostal")]
        public virtual ICollection<cliente> cliente { get; set; }
    }
}