// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CNCliente.Models
{
    public partial class concelho
    {
        public concelho()
        {
            cliente = new HashSet<cliente>();
            codpostal = new HashSet<codpostal>();
        }

        [Key]
        public int concelhoId { get; set; }
        [Required]
        public string concelhoNome { get; set; }
        [Required]
        public string concelhoCodigo { get; set; }
        public int concelhoNumero { get; set; }
        public int distrito_Id { get; set; }
        public int? regiao_Id { get; set; }

        [ForeignKey(nameof(distrito_Id))]
        [InverseProperty("concelho")]
        public virtual distrito distrito { get; set; }
        [InverseProperty("concelho")]
        public virtual ICollection<cliente> cliente { get; set; }
        [InverseProperty("concelho")]
        public virtual ICollection<codpostal> codpostal { get; set; }
    }
}