// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CNCliente.Models
{
    public partial class dimensao
    {
        public dimensao()
        {
            cliente = new HashSet<cliente>();
        }

        [Key]
        public int dimensaoId { get; set; }
        [Required]
        public string dimensaoNome { get; set; }

        [InverseProperty("dimensao")]
        public virtual ICollection<cliente> cliente { get; set; }
    }
}