// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CNCliente.Models
{
    public partial class distrito
    {
        public distrito()
        {
            cliente = new HashSet<cliente>();
            codpostal = new HashSet<codpostal>();
            concelho = new HashSet<concelho>();
        }

        [Key]
        public int distritoId { get; set; }
        [Required]
        public string distritoNome { get; set; }

        [InverseProperty("distrito")]
        public virtual ICollection<cliente> cliente { get; set; }
        [InverseProperty("distrito")]
        public virtual ICollection<codpostal> codpostal { get; set; }
        [InverseProperty("distrito")]
        public virtual ICollection<concelho> concelho { get; set; }
    }
}