// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CNCliente.Models
{
    public partial class estadoprojeto
    {
        public estadoprojeto()
        {
            projeto = new HashSet<projeto>();
        }

        [Key]
        public int estadoprojetoId { get; set; }
        [Required]
        public string estadoprojetoNome { get; set; }

        [InverseProperty("estado")]
        public virtual ICollection<projeto> projeto { get; set; }
    }
}