// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CNCliente.Models
{
    public partial class medida
    {
        public medida()
        {
            projeto = new HashSet<projeto>();
        }

        [Key]
        public int medidaId { get; set; }
        [Required]
        public string medidaNome { get; set; }
        [Required]
        public string medidaPrograma { get; set; }

        [InverseProperty("medida")]
        public virtual ICollection<projeto> projeto { get; set; }
    }
}