// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CNCliente.Models
{
    public partial class projeto
    {
        public projeto()
        {
            tarefa = new HashSet<tarefa>();
        }

        [Key]
        public int projetoId { get; set; }
        public string projetoNumero { get; set; }
        public string projetoDesignacao { get; set; }
        [Column(TypeName = "numeric(18, 2)")]
        public decimal? projetoValoraprovado { get; set; }
        [Column(TypeName = "numeric(18, 2)")]
        public decimal? projetoIncentivoaprovado { get; set; }
        [Column(TypeName = "numeric(18, 2)")]
        public decimal? projetoValorrealizado { get; set; }
        [Column(TypeName = "numeric(18, 2)")]
        public decimal? projetoIncentivorecebido { get; set; }
        [Column(TypeName = "date")]
        public DateTime? projetoDatasubmissao { get; set; }
        [Column(TypeName = "date")]
        public DateTime? projetoDatadecisao { get; set; }
        [Column(TypeName = "date")]
        public DateTime? projetoDatacontratacao { get; set; }
        [Column(TypeName = "date")]
        public DateTime? projetoDatainicio { get; set; }
        [Column(TypeName = "date")]
        public DateTime? projetoDatafim { get; set; }
        public string projetoResponsavel { get; set; }
        public int? cliente_Id { get; set; }
        public int? medida_Id { get; set; }
        public int? estado_Id { get; set; }

        [ForeignKey(nameof(cliente_Id))]
        [InverseProperty("projeto")]
        public virtual cliente cliente { get; set; }
        [ForeignKey(nameof(estado_Id))]
        [InverseProperty(nameof(estadoprojeto.projeto))]
        public virtual estadoprojeto estado { get; set; }
        [ForeignKey(nameof(medida_Id))]
        [InverseProperty("projeto")]
        public virtual medida medida { get; set; }
        [InverseProperty("projeto")]
        public virtual ICollection<tarefa> tarefa { get; set; }
    }
}