// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CNCliente.Models
{
    public partial class regiao
    {
        public regiao()
        {
            cliente = new HashSet<cliente>();
        }

        [Key]
        public int regiaoId { get; set; }
        [Required]
        [Column(TypeName = "text")]
        public string regiaoNome { get; set; }

        [InverseProperty("regiao")]
        public virtual ICollection<cliente> cliente { get; set; }
    }
}