// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CNCliente.Models
{
    public partial class tarefa
    {
        public tarefa()
        {
            InversetarefaParent = new HashSet<tarefa>();
        }

        [Key]
        public Int64 tarefaId { get; set; }
        public Int64 tarefaParentid { get; set; }
        public Int64 projeto_Id { get; set; }
        [Required]
        public string tarefaNome { get; set; }
        public DateTime tarefaDatahoraregisto { get; set; }
        public DateTime tarefaDatalimite { get; set; }
        public Int64 tarefaPosicao { get; set; }
        public Int64 utilizador_Id { get; set; }
        public bool tarefaEstado { get; set; }
        public bool tarefaTemfilho { get; set; }

        [ForeignKey(nameof(projeto_Id))]
        [InverseProperty("tarefa")]
        public virtual projeto projeto { get; set; }
        [ForeignKey(nameof(tarefaParentid))]
        [InverseProperty(nameof(tarefa.InversetarefaParent))]
        public virtual tarefa tarefaParent { get; set; }
        [ForeignKey(nameof(utilizador_Id))]
        [InverseProperty("tarefa")]
        public virtual utilizador utilizador { get; set; }
        [InverseProperty(nameof(tarefa.tarefaParent))]
        public virtual ICollection<tarefa> InversetarefaParent { get; set; }
    }
}