// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace CNCliente.Models
{
    public partial class utilizador
    {
        public utilizador()
        {
            tarefa = new HashSet<tarefa>();
        }

        public int utilizadorId { get; set; }
        public string utilizadorEmail { get; set; }
        public string utilizadorIniciais { get; set; }
        public string utilizadorNome { get; set; }

        public virtual ICollection<tarefa> tarefa { get; set; }
    }
}