// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CNCliente.Models
{
    public partial class utilizador
    {
        public utilizador()
        {
            tarefa = new HashSet<tarefa>();
        }

        [Key]
        public int utilizadorId { get; set; }
        [Required]
        [StringLength(50)]
        public string utilizadorEmail { get; set; }
        [Required]
        [StringLength(50)]
        public string utilizadorIniciais { get; set; }
        [Required]
        [StringLength(50)]
        public string utilizadorNome { get; set; }

        [InverseProperty("utilizador")]
        public virtual ICollection<tarefa> tarefa { get; set; }
    }
}